const products = [
    {
      "id": 1,
      "title": "No. 1 Backpack",
      "price": 109.95,
      "instock":100,
      "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    },
    {
      "id": 2,
      "title": "Slim Fit T-Shirts ",
      "price": 22.3,
      "instock":130,
      "image": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    },
    {
      "id": 3,
      "title": "Mens Jacket",
      "price": 55.99,
      "instock":110,
      "image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    },
    {
      "id": 4,
      "title": "Mens Slim Fit",
      "price": 15.99,
      "instock":10,
      "image": "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    },
    {
      "id": 5,
      "title": "Dragon  Bracelet",
      "price": 695,
      "instock":80,
      "image": "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    },
    {
      "id": 6,
      "title": "Solid Micropave ",
      "price": 168,
      "instock":170,
      "image": "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    },
    {
      "id": 7,
      "title": "White Princess",
      "price": 9.99,
      "instock":200,
      "image": "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    },
    {
      "id": 8,
      "title": "Pierced Steel",
      "price": 10.99,
      "instock":30,
      "image": "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    },
    {
      "id": 9,
      "title": "Portable Hard Drive",
      "price": 64,
      "instock":90,
      "image": "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    },
    {
      "id": 10,
      "title": "SanDisk SSD",
      "price": 109,
      "instock":167,
      "image": "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    },
];